name: "malware-analysis"
description: "REMnux + Windows sandbox + INetSim for malware detonation and analysis"
version: "1.0"
author: "labforge"

settings:
  lab_password: "labforge123!"

network:
  subnet: "auto"

services:
  - name: remnux
    image: "remnux/remnux-distro:focal"
    hostname: remnux
    ip_offset: 10
    platform: linux
    resources:
      memory: "4g"
      cpus: "2"
    ports:
      - "6901:6901"
    environment:
      VNC_PW: "${lab_password}"
    volumes:
      - remnux-data:/home/remnux
    restart: unless-stopped
    access:
      - label: "REMnux Desktop (noVNC)"
        url: "http://localhost:6901"
        credentials:
          username: "remnux"
          password: "${lab_password}"

  - name: windows-sandbox
    image: "dockurr/windows"
    hostname: windows
    ip_offset: 11
    platform: windows-docker
    resources:
      memory: "4g"
      cpus: "2"
    ports:
      - "8006:8006"
      - "3389:3389"
    environment:
      VERSION: "tiny11"
      RAM_SIZE: "4G"
      DISK_SIZE: "32G"
    volumes:
      - windows-data:/storage
    access:
      - label: "Windows Desktop (Web)"
        url: "http://localhost:8006"
      - label: "Windows RDP"
        url: "rdp://localhost:3389"

  - name: inetsim
    image: "remnux/inetsim"
    hostname: inetsim
    ip_offset: 12
    platform: linux
    resources:
      memory: "512m"
      cpus: "1"
    restart: unless-stopped
    access:
      - label: "INetSim"
        url: "Simulated internet services on subnet"

  - name: tcpdump
    image: "nicolaka/netshoot"
    hostname: tcpdump
    ip_offset: 13
    platform: linux
    cap_add:
      - NET_ADMIN
      - NET_RAW
    command: "tcpdump -i any -w /captures/traffic.pcap"
    volumes:
      - captures:/captures
    restart: unless-stopped
    access:
      - label: "Packet captures"
        url: "Volume: captures"

volumes:
  remnux-data: {}
  windows-data: {}
  captures: {}
